# -*- coding: utf-8 -*-
"""API_Test_Labs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12LPaK4YCT_CJVUqrgbMEih8CGlh4kVMl
"""

!pip install randomuser

from randomuser import RandomUser
import pandas as pd

# create Random User Object

r = RandomUser()

some_list = r.generate_users(10)
some_list

name = r.get_full_name()
name

for user in some_list:
  print (user.get_full_name(), ' ', user.get_email(), ' ', user.get_state())

#Generate Pictures
for user in some_list:
  print (user.get_picture())

# Generating a table with user data

def get_users():
  users = []
  for user in RandomUser.generate_users(10):
    users.append({'Name': user.get_full_name, 'Gender': user.get_gender(), 'City': user.get_city(), 'State': user.get_state(), 'Email': user.get_email(), 'D.O.B': user.get_dob(), 'Picture': user.get_picture()})
  return pd.DataFrame(users)

get_users()

df2 = pd.DataFrame(get_users())
df2.head()

df2

df2

# Using FruityVice API

import requests
import json
import pandas as pd

data = requests.get('https://fruityvice.com/api/fruit/all')
results = json.loads(data.text)

df = pd.DataFrame(results)
df.head()

#Flattening or normalizing data especially as relates to the nutrition column

df = pd.json_normalize(results)
df

#Extracting certain information, say cherry

cherry = df.loc[df["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

banana = df.loc [df['name'] == 'Banana']
banana.iloc[0]['nutritions.calories']

# Exercise 3

import requests
import pandas as pd
import json

data2 = requests.get('https://official-joke-api.appspot.com/jokes/ten')
results3 = json.loads(data2.text)
df4 = pd.DataFrame(results3)
df4.head()

#Dropping column

df4.drop(columns = ['type', 'id'], inplace = True)
df4

